- .github/PULL_REQUEST_TEMPLATE.md
This PR is to add a template for the pull-request.
> Adding a template for pull request

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/validate-pr.yml
This PR updates the PULL_REQUEST_TEMPLATE to include a regex pattern that ensures that the PR title has the issue. The pattern to be used is [Issue #<num>] followed by description
This PR updates the PULL_REQUEST_TEMPLATE to include a regex pattern that ensures that the PR title has the issue. The pattern to be used is [Issue #<num>] followed by description
No dependencies or pre-requisites
- Add screenshots here to illustrate changes.
> [Issue #97] Added rule that PR request should have the issue number in the title

- README.md
This PR addresses [Issue #119 ] by adding a new section to the README with detailed steps for:
Checking the current deployment version in the Google Cloud Console.
Accessing and filtering logs using the Logs Explorer.
> [Issue #119] Update README with instructions to check deployment version and view logs

- portal-app/package-lock.json
- portal-app/package.json
- portal-app/src/App.css
- portal-app/src/pages/lesson_detail/index.jsx
- portal-app/src/pages/view-content/index.jsx
- portal-app/yarn.lock
Added functionality to embed pdfs and videos (YouTube, Vimeo) within the content and lesson plan viewers. Also made layout improvements to both pages.
N/A
> [Issue #104] Added video embedding and improved layout for content and lesson plans

- portal-app/src/pages/my_plan/index.jsx
- Add screenshots here to illustrate changes.
> [Issue #136] make all lesson plans public

- portal-app/src/pages/lesson_generator/index.jsx
> [Issue #131] Fix submit button lesson plan

- portal-app/src/App.js
- portal-app/src/pages/edit_lesson/index.jsx
- portal-app/src/pages/lesson_detail/index.jsx
- server/controllers/lessonsController.js
- server/routes/lessons.js
##Additional Context
The exit button in edit page will redirect user back to the lesson detail page
> [Issue #141] Add edit feature in lesson plan detail page

- portal-app/src/components/ListView.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- [ X ] I have commented my code where necessary.
- 
> [Issue #139] Update dropdown category to Python

- portal-app/src/components/ListView.jsx
- portal-app/src/components/Navbar.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- ![Screenshot 2025-01-24 160644](https://github.com/user-attachments/assets/4435fa44-b1dd-412f-90e4-67a35baa2817)
> [Issue #146] Modify the top navbar with DIYA link and remove Team

- portal-app/src/pages/lesson_generator/index.jsx
- Add screenshots here to illustrate changes.
> [Issue #139] Correct Chemistry spelling

- portal-app/src/components/Navbar.jsx
- portal-app/src/hooks/useUserData.js
- portal-app/src/pages/edit_lesson/index.jsx
- portal-app/src/pages/lesson_detail/index.jsx
- server/index.js
- server/routes/user.js
> [Issue #129] Seperate UI and user data

- portal-app/src/components/Navbar.jsx
- This PR integrates a sign-up form into the navigation bar. Users can fill out the form and submit their details, which then redirects to Google authentication for further processing.
- Integration relies on Firebase for Google Authentication and Firestore for storing user data.
- [ X ] I have added tests that prove my fix is effective or my feature works.
- 
> [Issue #172] Task: Integrated sign-up form with navbar

- portal-app/src/components/Navbar.jsx
- portal-app/src/hooks/useUserData.js
- server/routes/user.js
> [Issue #170] Integrate signup flow frontend&backend

- portal-app/src/components/HomePage.jsx
> [Issue #157] Menu actions with roles

- portal-app/src/pages/lesson_detail/index.jsx
- Implemented a dropdown for lesson plan actions to replace separate buttons for "Edit", "Delete", and "Download".
- ![Screenshot 2025-02-18 204619](https://github.com/user-attachments/assets/5a08af09-a944-47f5-8194-65cd8eac2326)
> [Issue #190] Feature/dropdown lesson plan actions

- portal-app/src/pages/profile_detail/index.jsx
> [Issue #189] Show userType as label, not editable in profile page

- portal-app/src/pages/edit_lesson/index.jsx
- portal-app/src/pages/lesson_detail/index.jsx
- server/routes/user.js
> [Issue #191] Lesson plan role actions

- portal-app/src/pages/lesson_generator/index.jsx
- This PR updates the lesson plan dropdown to rename fields as follows:
Subject → Category
Added Type to the dropdown.
Grade Level → Level
- ![Screenshot 2025-02-25 153319](https://github.com/user-attachments/assets/13eb0fd4-7b2d-453e-8f95-8fab381781af)
> [Issue #200] Feature/rename dropdown lessonplan 

- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/src/pages/upload-content/index.jsx
- server/controllers/content_submission.js
> [Issue #199] update nugget creation flow in lesson plan generator

- portal-app/package-lock.json
- portal-app/package.json
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/yarn.lock
- Added a rich text editor (React Quill) for Lesson Description and all Sections in the Lesson Plan Generator.
- Users can now format text using bold, italics, underline, headings, bullet points, and links.
- Improved section handling by ensuring newly added sections also support the rich text editor.
- Installed react-quill for rich text editing
- ![Screenshot 2025-02-28 180533](https://github.com/user-attachments/assets/99ed858b-5af0-4d80-a2cb-1a828afe00c2)
> [Issue #165] Feature/text editor enhancements

- portal-app/src/pages/lesson_generator/index.jsx
- This PR renames the objective to lesson objective and converts it into a rich text editor. The button has been removed.
- ![Screenshot 2025-03-01 141724](https://github.com/user-attachments/assets/bbe2a51f-b877-4057-9579-e18c10e5296f)
> [Issue #204] Feature/Lesson objective rich text editor

- portal-app/src/components/HomePage.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/src/pages/my_plan/index.jsx
- Renames "+Add materials from portal" to "+Add Existing Nuggets"
- Renames "View my lesson plans" to "View Lesson Plans"
- Renames "My Plans" to "Plans"
- [ X ] Other (please specify): Task 
- ![Screenshot 2025-03-04 211843](https://github.com/user-attachments/assets/d3b3abf4-c503-41a7-b3d6-1a628bfcddf8)
- ![Screenshot 2025-03-04 212022](https://github.com/user-attachments/assets/e4e42689-5dc8-4fcc-a334-0f83d2e36695)
- ![Screenshot 2025-03-04 212101](https://github.com/user-attachments/assets/cced10c2-f353-43d6-9bb8-6213609898c2)
- ![Screenshot 2025-03-04 212136](https://github.com/user-attachments/assets/7bec9b10-845e-43d4-9da8-57dfc0ebcf3e)
> [Issue #217] Task/Rename button name and plans

- portal-app/src/pages/edit_content/index.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/src/pages/upload-content/index.jsx
- server/controllers/lessonsController.js
- server/controllers/unitsController.js
- server/controllers/update_submission.js
> [Issue #140] Public private setting

- portal-app/src/pages/edit_lesson/index.jsx
- portal-app/src/pages/lesson_detail/index.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/src/pages/my_plan/index.jsx
- server/controllers/lessonsController.js
> [Issue #208] Update lesson plan backend & display

- portal-app/src/pages/edit_lesson/index.jsx
- portal-app/src/pages/lesson_detail/index.jsx
- portal-app/src/pages/view-content/index.jsx
> [Issue #218] Add create nugget in edit

- portal-app/src/pages/lesson_generator/index.jsx
- server/controllers/unitsController.js
- server/routes/units.js
> [Issue #198] Add save current session

- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/src/pages/upload-content/index.jsx
> [Issue #201] pass lesson plan value to nugget create and select

- portal-app/src/pages/lesson_detail/index.jsx
- portal-app/src/pages/my_plan/index.jsx
- server/controllers/lessonsController.js
- server/routes/lessons.js
> [Issue #206] Add a dropdown to display private plans created by current user

- portal-app/src/pages/lesson_detail/index.jsx
- portal-app/src/pages/my_plan/index.jsx
- server/controllers/lessonsController.js
- server/routes/lessons.js
> [Issue #230] Sort of lesson plan

- portal-app/src/pages/my_plan/index.jsx
- This PR adds a checkbox to the lesson plan's card, visible only to admins.
-  When an admin selects one or more lesson plans, a "Create Module" button appears.
-  Clicking the "Create Module" button navigates the user to the module creation page.
- [ X ] I have commented my code where necessary.
- ![Screenshot 2025-03-19 122259](https://github.com/user-attachments/assets/c8365358-3d2d-47e9-a179-984bdf4af460)
> [Issue #237] Feature/Add checkbox and create module button to plan page

- portal-app/src/components/Module.jsx
-  This PR implements the reorder feature for the lesson plan list table, allowing users to rearrange lesson plans interactively.
-  No additional dependencies or pre-requisites are required for this change.
- [ X ] I have commented my code where necessary.
- [ X ] I have added tests that prove my fix is effective or my feature works.
- ![Screenshot 2025-03-21 134255](https://github.com/user-attachments/assets/54a7e237-9fca-4056-b395-21ed3ec83fa3)
- ![Screenshot 2025-03-21 134310](https://github.com/user-attachments/assets/2a2b4c50-875d-4b62-a147-e039f090594c)
> [Issue #235] Feature/Added reorder feature to lesson plan list table

- portal-app/src/pages/module_detail/index.jsx
> [Issue #244] Update UI in module page

- portal-app/src/pages/module_detail/index.jsx
> [Issue #248] remove heading in view module

- portal-app/src/pages/module_detail/index.jsx
- Added an Exit button to the Module Detail page to allow users to return to the homepage from view mode.
- [ X ] I have added tests that prove my fix is effective or my feature works.
- ![Screenshot 2025-03-28 134115](https://github.com/user-attachments/assets/08f92fdb-051e-4ac3-b0c9-49aade8a7a72)
> [Issue #261] Feature/module exit button

- portal-app/src/pages/module_detail/index.jsx
> [Issue #249] restrict edit module only for admin

- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/lesson_generator/index.jsx
- portal-app/src/pages/module_detail/index.jsx
> [Issue #236] add lessonplan popup

- portal-app/src/pages/lesson_generator/index.jsx
- Minor UI fix in Lesson Generator form input field
- [ X ] I have added tests that prove my fix is effective or my feature works.
- ![image](https://github.com/user-attachments/assets/85032b5e-373c-41d6-9c56-ff2e76349573)
> [Issue #281] Fix/Updated placeholder from 'duration' to 'Duration'

- portal-app/src/components/ExploreModulesSection.jsx
- portal-app/src/firebase/firebaseConfig.js
Issue Number: Closes #289 
added backend for testimonial carousel
- backend update
- [X ] My code follows the style guidelines of this project.
> [Issue #289] added backend for testimonial carousel

- portal-app/src/components/ExploreModulesSection.jsx
When someone is not logged in and clicks the buttons under the For Teachers or For Students sections, a popup should show saying to log in or sign up to access. Additionally if a student tries to access the teacher materials or vice versa, the popup should show up as well. If user is meant to see the clicked content it opens up a new page.
- [X ] New feature
> [Issue #292] added buttons and popup for teach and student section

- portal-app/src/components/ExploreModulesSection.jsx
Pull modules from Firebase and populate on frontend. Create the filters for the modules.
- [ X] New feature
> [Issue #308] Update/add filter and search teacher free

- portal-app/src/components/ExploreModulesSection.jsx
> [Issue #310] Fix h2 tag

- portal-app/src/components/ExploreModulesSection.jsx
- [X ] Issue Number: Closes #325
Change the text "Paid" and "Free" on the filter and search content to be an open and closed lock instead. Add the locked/unlocked filters.
- [X ] New feature
- [ X] I have commented my code where necessary.
- [ X] I have added tests that prove my fix is effective or my feature works.
> [Issue #325] updated filter and search with locked unlocked

- portal-app/src/App.js
- portal-app/src/components/ListView.jsx
- portal-app/src/components/Navbar.jsx
- portal-app/src/pages/upgrade_page/UpgradePage.jsx
- portal-app/yarn.lock
Design a responsive, three-column layout displaying Free, Premium, and Enterprise plans
Populate each column with a clear list of features and offerings for the respective plan
Match UI/UX to the attached screenshot and existing platform style
> [Issue #328] UI Frontend for Upgrade Page 

- portal-app/.env.development
- portal-app/package-lock.json
- portal-app/package.json
- portal-app/src/App.js
- portal-app/src/hooks/useUserData.js
- portal-app/src/pages/payment/PaymentPage.jsx
- portal-app/src/pages/upgrade_page/UpgradePage.jsx
- portal-app/yarn.lock
> [Issue #329] CTA buttons on upgrade and payment page

- portal-app/src/App.js
- portal-app/src/components/ExploreModulesSection.jsx
- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/lesson-plans/builder.jsx
- portal-app/src/pages/lesson-plans/drafts.jsx
- portal-app/src/pages/nugget-details.jsx
- portal-app/src/pages/upload-content/index.jsx
- [ x] Issue Number: Closes #337
finished implementation of entire lesson plan builder, merging code
- [X ] Bug fix
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my code.
- [ X] I have commented my code where necessary.
- [X ] I have added tests that prove my fix is effective or my feature works.
> [Issue #337] lesson plan builder implementation

- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/lesson-plans/builder.jsx
- portal-app/src/pages/nugget-builder.jsx
- portal-app/src/pages/nugget-details.jsx
- portal-app/src/pages/upload-content/index.jsx
- [ X] Issue Number: Closes #337
update the lesson plan builder nuggets in sections to have title linked to nugget page, save draft button should not require description. Also edit nugget builder to make dropdowns multi select.
- [X ] Bug fix
- [ X] I have commented my code where necessary.
- [X ] I have added tests that prove my fix is effective or my feature works.
> [Issue #337] Lesson plan builder v2

- portal-app/src/pages/lesson-plans/builder.jsx
- portal-app/src/pages/nugget-builder.jsx
- portal-app/src/pages/nugget-details.jsx
update the lesson plan builder nuggets in sections to have title linked to nugget page, save draft button should not require description. Also edit nugget builder to make dropdowns multi select.
- [ X] Bug fix
- [X ] I have performed a self-review of my code.
- [X ] I have added tests that prove my fix is effective or my feature works.
> [Issue #335] lesson plan builder updates

- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/nugget-details.jsx
- portal-app/src/pages/upload-content/index.jsx
- [ X] Issue Number: Closes #337
update the lesson plan builder nuggets in sections to have title linked to nugget page, save draft button should not require description. Also edit nugget builder to make dropdowns multi select.
- [X ] Bug fix
- [X ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my code.
- [x ] I have commented my code where necessary.
- [x ] I have added tests that prove my fix is effective or my feature works.
> [Issue #337] updates to nuggets

- portal-app/src/App.js
- portal-app/src/components/ExploreModulesSection.jsx
- portal-app/src/components/OverlayTileView.jsx
- portal-app/src/pages/lesson-plans/builder.jsx
- portal-app/src/pages/lesson-plans/drafts.jsx
- portal-app/src/pages/module_builder/OverlayTileView.jsx
- portal-app/src/pages/module_builder/builder.jsx
- portal-app/src/pages/module_builder/drafts.jsx
- portal-app/src/pages/module_builder/index.jsx
- portal-app/src/pages/module_builder/lesson-details.jsx
- portal-app/src/pages/upload-content/index.jsx
Implemented a "Module Builder" feature in the DIYA Ed Portal. This feature allows users to create comprehensive modules by entering lesson details, categorizing by subject and level, and selecting (or creating) 'lesson plans' to include in the module. Lesson Plan search and selection should be user-friendly and filterable by category and level.
- [X ] New feature
- [X ] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my code.
- [X ] I have added tests that prove my fix is effective or my feature works.
> [Issue #349] Implemented module builder

- portal-app/package-lock.json
- portal-app/package.json
- portal-app/src/App.js
- portal-app/src/assets/images/index.js
- portal-app/src/components/ContentDetails.jsx
- portal-app/src/components/ExploreModulesSection.jsx
- portal-app/src/components/HeroSection.jsx
- portal-app/src/components/HomePage.jsx
- portal-app/src/components/LessonDetails.jsx
- portal-app/src/components/ModuleDetails.jsx
- portal-app/src/components/Navbar.jsx
- portal-app/src/pages/cancel-subscription/CancelSubscriptionPage.jsx
- portal-app/src/pages/module_builder/builder.jsx
- portal-app/src/pages/module_detail/index.jsx
- portal-app/src/pages/payment/PaymentPage.jsx
- portal-app/src/pages/payment/YearlyPaymentPage.jsx
- portal-app/src/pages/teacherplus/teacherplusPage.jsx
- portal-app/src/pages/upgrade_page/UpgradePage.jsx
- portal-app/yarn.lock
- server/config/firebaseConfig.js
- server/routes/payment.js
- server/routes/subscription.js
- This issue tracks the merge of the release_20250807 branch into main. It includes updates and final changes prepared for deployment in this release cycle.
> [Issue #386] Merge release 20250807
